#!/usr/bin/env python3
#
# Automates the release checklist item in `createrelease`:
#
#   # Check every isPremiumEnabled call: TODO write helper script
#   # - every id should be in --errorlist
#   # - premiumaddon: check coverage.py
#
# Two checks are performed:
#
#  1. Every id passed to isPremiumEnabled("...") in lib/ must be a real,
#     known Cppcheck error id (i.e. it must show up in `cppcheck
#     --errorlist`). Otherwise the premium check can never actually be
#     turned on/off since its id does not exist.
#
#  2. Every Cppcheck id referenced by the premium addon's compliance
#     mapping tables (MISRA/CERT/AUTOSAR/CWE -> Cppcheck id, generated by
#     `coverage.py --id`) must also show up in `cppcheck --errorlist`.
#     Otherwise the mapping refers to an id that has been renamed or
#     removed.
#
# A warning is printed for every id that fails a check; exit status is 1
# if any warning was printed, 0 otherwise.
#
# Usage:
#   tools/release-check-premium-ids.py [path-to-addon/coverage]
#
# The addon/coverage directory defaults to ../addon/coverage (relative to
# this repo, i.e. a checkout of the premium addon repo next to this one).
# If it can't be found, check 2 is skipped.

import argparse
import glob
import os
import re
import subprocess
import sys

REPO_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
CPPCHECK_BIN = os.path.join(REPO_DIR, 'cppcheck')

ID_RE = re.compile(r' id="([^"]*)"')
IS_PREMIUM_ENABLED_RE = re.compile(r'isPremiumEnabled\s*\(\s*"([^"]*)"')

warning_count = 0


def warn(message):
    global warning_count
    warning_count += 1
    print('warning: ' + message, file=sys.stderr)


def get_errorlist_ids():
    out = subprocess.check_output([CPPCHECK_BIN, '--errorlist'], universal_newlines=True)
    return set(ID_RE.findall(out))


def get_is_premium_enabled_ids():
    ids = set()
    for filename in glob.glob(os.path.join(REPO_DIR, 'lib', '*.cpp')) + glob.glob(os.path.join(REPO_DIR, 'lib', '*.h')):
        with open(filename, 'rt', encoding='utf-8') as f:
            ids.update(IS_PREMIUM_ENABLED_RE.findall(f.read()))
    return ids


def get_addon_coverage_ids(addon_coverage_dir):
    coverage_py = os.path.join(addon_coverage_dir, 'coverage.py')
    if not os.path.isfile(coverage_py):
        print(f"(skipped premium addon coverage.py check: '{coverage_py}' not found)", file=sys.stderr)
        return None

    ids_files = glob.glob(os.path.join(addon_coverage_dir, 'ids-*.txt'))
    for f in ids_files:
        os.remove(f)

    env = dict(os.environ, CPPCHECK_REPO=REPO_DIR)
    subprocess.check_call(['python3', 'coverage.py', '--id'], cwd=addon_coverage_dir, env=env, stdout=subprocess.DEVNULL)

    ids = set()
    ids_files = glob.glob(os.path.join(addon_coverage_dir, 'ids-*.txt'))
    for filename in ids_files:
        with open(filename, 'rt', encoding='utf-8') as f:
            ids.update(line.strip() for line in f if line.strip())
        os.remove(filename)
    return ids


def main():
    parser = argparse.ArgumentParser(description='Check that isPremiumEnabled() ids and premium addon coverage ids are known Cppcheck error ids.')
    parser.add_argument('addon_coverage_dir', nargs='?', default=os.path.join(REPO_DIR, '..', 'addon', 'coverage'),
                         help='path to the premium addon coverage/ directory (default: ../addon/coverage)')
    args = parser.parse_args()

    if not os.access(CPPCHECK_BIN, os.X_OK):
        print(f"error: '{CPPCHECK_BIN}' not found or not executable, build it first (make -j$(nproc))", file=sys.stderr)
        return 1

    errorlist_ids = get_errorlist_ids()

    for id_ in sorted(get_is_premium_enabled_ids() - errorlist_ids):
        warn(f'isPremiumEnabled("{id_}") but there is no such id in --errorlist')

    addon_coverage_dir = os.path.realpath(args.addon_coverage_dir)
    addon_ids = get_addon_coverage_ids(addon_coverage_dir)
    if addon_ids is not None:
        for id_ in sorted(addon_ids - errorlist_ids):
            warn(f'premium addon coverage.py references id "{id_}" but there is no such id in --errorlist')

    return 1 if warning_count else 0


if __name__ == '__main__':
    sys.exit(main())
